### ISSUE TITLE
Key bug

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#1]
I'm running this on a Mac, and after changing some things to make it work (I am considering doing a PR to the repo for them), I get this error

voidref@AlSi ~/s/textcom> ./textcom.py 
Bradford: "Welcome Commander. We've discovered an Alien Base, and it's your job to send someone out to deal with it."
Bradford: "Choose a soldier from the 3 below to go on the mission."
1: 
Rookie Violet Dan Voorn -  5 HP - 62 Aim
Items: Ballistic Rifle, Nano Serum, Nano Serum

2: 
Rookie Becks Nerman -  4 HP - 58 Aim
Items: Ballistic Carbine, Scope, Nano Serum

3: 
Rookie Peter Beardly -  3 HP - 67 Aim
Items: Ballistic Carbine, Nano Serum, Frag Grenade
#3

Peter Beardly: "Ready for duty, Commander!"
HP - 3
AP - 15
1: "Advance"
2: "(8AP) Reload"
#1

Peter Beardly: "Roger that, moving up!"
Traceback (most recent call last):
  File "./textcom.py", line 914, in <module>
    playerTurn()
  File "./textcom.py", line 320, in playerTurn
    checkspot(roomNo)
  File "./textcom.py", line 286, in checkspot
    p(0,room[roomNo][i].name()+" spotted!")
  File "./textcom.py", line 266, in name
    return (" ("+self.species+") "+aranks[self.rank]+" "+self.fName+" "+self.lName)
KeyError: -1.0

I'm not as familiar with Python as I should be, so I am not sure why self.rank is -1.0 somehow (I think)

**Comment by voidref** [comment]
It looks like roomNo is being set as -1 somehow.

**Comment by ewolsasdf** [comment]
roomNo is being initialized as -1 and roomNo is only incremented in playerTurn which only occurs AFTER aliens are generated for the room. Alien rank is using roomNo to determine it's value, so aliens have a chance to be generated with a rank of -1 which is what is causing the KeyError.

**Comment by ewolsasdf** [comment]
Moving roomNo = 0 above alien generation should fix this issue.

**Comment by TachyonNZ** [comment]
Ah, I didn't realise that this might happen.

**Comment by TachyonNZ** [comment]
Issue resolved.
