### ISSUE TITLE
Typo for attribute

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#11]
Violet Civilian: "Reached an access point, Commander. Requesting additional goods!"
Violet Civilian: "We only have a short time before they close the access point!"
Fragments: 63
Elerium: 31
Meld: 30
Alloy: 12
Time: 60
1: "Advance"
2: "(60 Time) (15m) Insta-Genemod: Depth Perception (+5 aim)"
3: "(60 Time) (15m) Micro-Augment: Reflex Servomotors (+2 AP)"
5: "(60 Time) (20m) Insta-Genemod: Muscle Regeneration (+5 HP)"
6: "(60 Time) (20m) Micro-Augment: Grenade Launcher (+2 Frag Grenades)"
7: "(40 Time) (20e) (40f) Get Laser Rifle"
     (~4dmg), infinite ammo
8: "(40 Time) (10e) (30f) Get Laser Carbine"
     (~3dmg), infinite ammo, +10% aim
9: "(30 Time) (10m) (10f) Get Nano Serum"
10: "(30 Time) (20f) (4a) Get Frag Grenade"
11: "(20 Time) (5m) Recuperate (+1 HP)"
12: "(20 Time) Reload Weapon"
13: "(60 Time) Advance (Skip this Drop Zone)"
#7

LaserRifle
Fragments: 23
Elerium: 11
Meld: 30
Alloy: 12
Time: 60
1: "Advance"
2: "(60 Time) (15m) Insta-Genemod: Depth Perception (+5 aim)"
3: "(60 Time) (15m) Micro-Augment: Reflex Servomotors (+2 AP)"
5: "(60 Time) (20m) Insta-Genemod: Muscle Regeneration (+5 HP)"
6: "(60 Time) (20m) Micro-Augment: Grenade Launcher (+2 Frag Grenades)"
7: "(30 Time) (10m) (10f) Get Nano Serum"
8: "(30 Time) (20f) (4a) Get Frag Grenade"
9: "(20 Time) (5m) Recuperate (+1 HP)"
10: "(20 Time) Reload Weapon"
11: "(60 Time) Advance (Skip this Drop Zone)"
#5

HPBonus
Traceback (most recent call last):
  File "./textcom.py", line 1510, in <module>
    playerTurn()
  File "./textcom.py", line 807, in playerTurn
    soldier.HP += 5
AttributeError: 'Soldier' object has no attribute 'HP'

This is kinda what sucks about loose type languages, you don't know you have a problem until it crashes on someone.

Maybe I'll port this to Swift! ;)

**Comment by TachyonNZ** [comment]
Lowercase, dammit, lowercase. :(
