### ISSUE TITLE
Alien overwatch out of order

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#12]
I feel like the soldier should say they are moving to full cover before they are shot at.

1: "Overwatch"
2: "(3AP) Reposition"
3: "Hunker Down"
4: "End Turn"
#2

(Sectoid) Soldier Glerp Glommery reacts!
 Missed!
David Green: "Moving to Full cover!"

**Comment by TachyonNZ** [comment]
Resolved in a version which I will add shortly
