### ISSUE TITLE
Did you mean for probability to be 4%?

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#15]
this code

```
def drop():
    itemdrop = rd.randrange(0,5)
    if rd.randrange(1,100) < 5:
```

looks like it generates a number from 1 to 100, and then looks to see if it's 4 or less, resulting in a 4% drop rate instead of 5%

`rd.randrange(0,99) < 5` would be 5%.
=)

**Comment by TachyonNZ** [comment]
That was Flimberger's adjustment, I believe. I'll fix that tonight.
