### ISSUE TITLE
[Feature request] Common actions to always have same keys

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#24]
Change the common actions to letters, something like 'O' == overwatch, 'H' = Hunker, and reserve the numbers for shots at Aayys

**Comment by voidref** [comment]
I have an implementation of this if you are interested in seeing it.

At the moment it looks like

```
[1]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Sectoid) Peon Glorp Glupple - 2 HP - (60%)
[2]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Sectoid) Peon Glup Glarp - 2 HP - (60%)
[o]  (6 AP) Overwatch
[r]  (8 AP) Reload
[5]  (10 AP) (+4 HP) (10 AP) Use Nano-Serum
[p]  (3 AP) Reposition
[h]  (1 AP) Hunker down
[e] End turn
> g
'g is not a valid action
> 6
'6 is not a valid action
>    
```

**Comment by voidref** [comment]
I improved the impl to add keys for items as well:

```
[1]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Sectoid) Peon Glarp Glorple - 2 HP - (38%)
[o]  (6 AP) Overwatch
[g]  (10 AP) (2 dmg) (10 AP) Use Frag Grenade
[g]  (10 AP) (2 dmg) (10 AP) Use Frag Grenade
[p]  (3 AP) Reposition
[e] End turn
```

Yes, 'g' is repeated but it doesn't matter, it just uses the first one. =)

**Comment by TachyonNZ** [comment]
Looks good, mind sharing the code for it? I'm just going through all of these bugs now, so there'll be plenty of merge errors. :)

**Comment by voidref** [comment]
Here's a branch:

https://github.com/voidref/textcom/blob/voidyfixes/textcom.py

**Comment by voidref** [comment]
PR #36 ready!
