### ISSUE TITLE
Hunker has no actual affect

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#25]
Looking at the code for when the aliens shoot, it ignores the hunker state.

**Comment by TachyonNZ** [comment]
It does: "cthplayer = (alium.aim - soldier.cover) - soldier.hunkerbonus" (line 1473), in alienTurn()

**Comment by voidref** [comment]
That's only for display, it does not use cthplayer for actual hit detection chance.

**Comment by TachyonNZ** [comment]
It should do now. If it doesn't I'll have another look at lunch.
