### ISSUE TITLE
Game thinks latest weapon is the one you want to use

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#31]
If you have a plasma rifle, and then you recover a light plasma rifle, it will switch to the light one, even though the regular does more damage.

**Comment by TachyonNZ** [comment]
I'm not sure if I want to change this. "That's XCOM!"

I probably will though, at some point.

**Comment by voidref** [comment]
Haha, maybe we can add a simple: "Keep the X or the Y?" question.
