### ISSUE TITLE
Aliens overwatch is sticky

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#6]
This happend:

Alien Activity!
 (Muton) Commander Holk Jefferson runs to Half cover!
 (Thin Man) Supreme Commander P. Anderson runs to Half cover!
HP - 7
AP - 18
1: "(8AP) Reload Weapon"
2: "(2dmg)(10AP) Throw Frag Grenade"
3: "(4dmg)(15AP) Throw Alien Grenade"
4: "(3AP) Reposition"
5: "End Turn"
#1

HP - 7
AP - 10
1: "(~5dmg)(6AP) Fire Light Plasma Rifle : Commander Holk Jefferson - 12 HP - 98%"
2: "(~5dmg)(6AP) Fire Light Plasma Rifle : Supreme Commander P. Anderson - 11 HP - 98%"
3: "Overwatch"
4: "(2dmg)(10AP) Throw Frag Grenade"
5: "(3AP) Reposition"
6: "End Turn"
#2

Central Officer Bradford: "WHAT HAVE YOU DONE?!"
_Whap-whap-whap_
5 damage!
HP - 7
AP - 4
1: "Overwatch"
2: "(3AP) Reposition"
3: "End Turn"
#2

 (Muton) Commander Holk Jefferson reacts!
 Missed!
 (Thin Man) Supreme Commander P. Anderson reacts!
4 damage!
Central Officer Bradford: "Moving to...wait...that's CLOSE RANGE!"

I think the aliens went on overwatch, then moved, which should have taken them off overwatch, but didn't.

**Comment by TachyonNZ** [comment]
Moving now removes alien overwatch. Resolved. :)
