### ISSUE TITLE
Alien's ghosts run to half cover

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#9]
I killed an alien on overwatch, but his lifeless body made it to half cover:

Alien Activity!
(Sectoid) Peon Glup Gloopley runs to Full cover!
HP - 4
AP - 13
1: "(8AP) Reload Weapon"
2: "(2dmg)(10AP) Throw Frag Grenade"
3: "(3AP) Reposition"
4: "End Turn"
#1

HP - 4
AP - 5
1: "Overwatch"
2: "(3AP) Reposition"
3: "End Turn"
#2

Nina Beegle: "Moving to Full cover!"
(Sectoid) Peon Glup Gloopleyis flanked!
HP - 4
AP - 2
1: "Overwatch"
2: "Hunker Down"
3: "End Turn"
#1

Nina Beegle: "Got it, on Overwatch."
Rookie Beegle is out of AP!
Alien Activity!
(Sectoid) Peon Glup Gloopley runs to Full cover!
Rookie Beegle reacts!
2 damage!
(Sectoid) Peon Glup Gloopley died!
(Sectoid) Peon Glup Gloopley runs to Half cover!
HP - 4
AP - 13
1: "Advance"
2: "(8AP) Reload"
#

**Comment by TachyonNZ** [comment]
Resolved, hopefully!
